// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ClothesPb;
@class HousePb;
@class PetPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserPbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserPbRoot : GPBRootObject
@end

#pragma mark - UserPb

typedef GPB_ENUM(UserPb_FieldNumber) {
  UserPb_FieldNumber_ResultMessage = 1,
  UserPb_FieldNumber_ResultCode = 2,
  UserPb_FieldNumber_Success = 3,
  UserPb_FieldNumber_UserName = 4,
  UserPb_FieldNumber_FavouriteSport = 5,
  UserPb_FieldNumber_FavouriteMovie = 6,
  UserPb_FieldNumber_HasMarried = 7,
  UserPb_FieldNumber_EducationEnum = 8,
  UserPb_FieldNumber_Age = 9,
  UserPb_FieldNumber_PsychologicalAge = 10,
  UserPb_FieldNumber_Pet = 11,
  UserPb_FieldNumber_OwnHousesArray = 12,
  UserPb_FieldNumber_Wardrobes = 13,
};

#pragma Typewriter(generate=UserPbModel)
#pragma Typewriter(inherit=TypewriterBaseModel)
#pragma Typewriter(specialIncludeSuffix=.pbobjc.h)
#pragma Typewriter(implement={NSObject})
#pragma Typewriter(filter={success})
#pragma Typewriter(predicateFilter=SELF CONTAINS %@ OR SELF CONTAINS %@, result, _Count)
#pragma Typewriter(immutable)
#pragma Typewriter(rewritten={Rewritten(on=userName,name=name),\
                              Rewritten(on=educationEnum,name=education,type=EducationLevel),\
                              Rewritten(on=pet,type=$ref(PetPb.pbobjc.h)),\
                              Rewritten(on=ownHousesArray,name=houses,type=$ref(HousePb.pbobjc.h)),\
                              Rewritten(on=wardrobes,type=$ref(ClothesPb.pbobjc.h))})

@interface UserPb : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultCode;

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *favouriteSport;

@property(nonatomic, readwrite, copy, null_resettable) NSString *favouriteMovie;

@property(nonatomic, readwrite) BOOL hasMarried;

@property(nonatomic, readwrite, copy, null_resettable) NSString *educationEnum;

@property(nonatomic, readwrite) uint32_t age;

@property(nonatomic, readwrite) int32_t psychologicalAge;

@property(nonatomic, readwrite, strong, null_resettable) PetPb *pet;
/** Test to see if @c pet has been set. */
@property(nonatomic, readwrite) BOOL hasPet;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<HousePb*> *ownHousesArray;
/** The number of items in @c ownHousesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger ownHousesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, ClothesPb*> *wardrobes;
/** The number of items in @c wardrobes without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wardrobes_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
