//
//  AppModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface AppModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy) NSString *type;
@property (nonatomic, readwrite, copy, nullable) NSString *producer;
+ (nullable instancetype)modelWithJSON:(id)json;
- (nullable instancetype)initWithJSON:(id)json;
@end

@interface AppModel (Extension)
- (id)initializerPreprocess:(id)preprocess;
@end

NS_ASSUME_NONNULL_END
