//
//  AppModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "AppModel.h"

@implementation AppModel
+ (nullable instancetype)modelWithJSON:(id)json
{
    return [[self alloc] initWithJSON:json];
}
- (nullable instancetype)initWithJSON:(id)json
{
    NSParameterAssert(json);
    if (!(self = [super init])) {
        return nil;
    }
    id preprocess = [self initializerPreprocess:json];
    if (![self propertyMapWithJSON:preprocess]) {
        return nil;
    }
    return self;
}
+ (NSDictionary *)customPropertyMapper
{
    return @{@"producer" : @"company"};
}
@end

@implementation AppModel (Extension)
- (id)initializerPreprocess:(id)preprocess
{
    return preprocess;
}
@end
