//
//  ClothesModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class ClothesProto;

NS_ASSUME_NONNULL_BEGIN

@interface ClothesModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readwrite, copy) NSString *type;
@property (nonatomic, readwrite, assign) UInt32 price;
@property (nonatomic, readwrite, copy) NSString *brand;
+ (nullable instancetype)modelWithClothesProto:(ClothesProto *)prototype objectId:(nullable NSString *)objectId;
- (nullable instancetype)initWithClothesProto:(ClothesProto *)prototype objectId:(nullable NSString *)objectId;
@end

@interface ClothesModel (Extension)
+ (void)unidirectionalDataflow:(ClothesModel *)model objectId:(NSString *)objectId;
@end

NS_ASSUME_NONNULL_END
