//
//  ClothesModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "ClothesModel.h"
#import "ClothesProto.h"

@implementation ClothesModel
- (instancetype)init UNAVAILABLE_ATTRIBUTE
{
    NSAssert(NO, @"please use designed initializer instead!");
    return nil;
}
+ (nullable instancetype)modelWithClothesProto:(ClothesProto *)prototype objectId:(nullable NSString *)objectId
{
    return [[self alloc] initWithClothesProto:prototype objectId:objectId];
}
- (nullable instancetype)initWithClothesProto:(ClothesProto *)prototype objectId:(nullable NSString *)objectId
{
    NSParameterAssert(prototype);
    if (!(self = [super init])) {
        return nil;
    }
    [self propertyMapWithPrototype:prototype mapping:@{@"type" : @"type",
                                                       @"price" : @"price",
                                                       @"brand" : @"brand"}];
    self->_objectId = objectId;
    [ClothesModel unidirectionalDataflow:self objectId:self.objectId];
    return self;
}
@end

@implementation ClothesModel (Extension)
+ (void)unidirectionalDataflow:(ClothesModel *)model objectId:(NSString *)objectId
{
    // unidirectional data flow
}
@end
