//
//  HeadPhoneModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface HeadPhoneModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readwrite, copy, nullable) NSString *color;
@property (nonatomic, readwrite, assign) UInt32 battery;
@property (nonatomic, readwrite, assign) UInt64 price;
@property (nonatomic, readwrite, assign) HeadPhoneBrand brand;
+ (nullable instancetype)modelWithJSON:(id)json objectId:(NSString *)objectId;
- (nullable instancetype)initWithJSON:(id)json objectId:(NSString *)objectId;
@end

@interface HeadPhoneModel (Extension)
+ (void)unidirectionalDataflow:(HeadPhoneModel *)model objectId:(NSString *)objectId;
@end

NS_ASSUME_NONNULL_END
