//
//  HeadPhoneModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "HeadPhoneModel.h"

@implementation HeadPhoneModel
+ (nullable instancetype)modelWithJSON:(id)json objectId:(NSString *)objectId
{
    return [[self alloc] initWithJSON:json objectId:objectId];
}
- (nullable instancetype)initWithJSON:(id)json objectId:(NSString *)objectId
{
    NSParameterAssert(json);
    if (!(self = [super init])) {
        return nil;
    }
    if (![self propertyMapWithJSON:json]) {
        return nil;
    }
    self->_objectId = objectId;
    [HeadPhoneModel unidirectionalDataflow:self objectId:self.objectId];
    return self;
}
@end

@implementation HeadPhoneModel (Extension)
+ (void)unidirectionalDataflow:(HeadPhoneModel *)model objectId:(NSString *)objectId
{
    // unidirectional data flow
}
@end
