//
//  HousePbModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class HousePb;

NS_ASSUME_NONNULL_BEGIN

@interface HousePbModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readonly, assign) UInt32 area;
@property (nonatomic, readonly, assign) BOOL isSchoolDistrict;
@property (nonatomic, readonly, copy) NSString *location;
+ (nullable instancetype)modelWithHousePb:(HousePb *)prototype;
- (nullable instancetype)initWithHousePb:(HousePb *)prototype;
@end

NS_ASSUME_NONNULL_END
