//
//  HouseModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class HouseProto;

NS_ASSUME_NONNULL_BEGIN

@interface HouseModel : TypewriterBaseModel<NSObject>
/**
 * 平米数
 */
@property (nonatomic, readonly, assign) UInt32 area;
/**
 * 是否学区房
 */
@property (nonatomic, readonly, assign) BOOL isSchoolDistrict;
/**
 * 位置
 */
@property (nonatomic, readonly, copy) NSString *location;
+ (nullable instancetype)modelWithHouseProto:(HouseProto *)prototype;
- (nullable instancetype)initWithHouseProto:(HouseProto *)prototype;
@end

NS_ASSUME_NONNULL_END
