//
//  HousePbModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "HousePbModel.h"
#import "HousePb.pbobjc.h"

@implementation HousePbModel
+ (nullable instancetype)modelWithHousePb:(HousePb *)prototype
{
    return [[self alloc] initWithHousePb:prototype];
}
- (nullable instancetype)initWithHousePb:(HousePb *)prototype
{
    NSParameterAssert(prototype);
    if (!(self = [super init])) {
        return nil;
    }
    [self propertyMapWithPrototype:prototype mapping:@{@"area" : @"area",
                                                       @"isSchoolDistrict" : @"isSchoolDistrict",
                                                       @"location" : @"location"}];
    return self;
}
@end
