//
//  HouseModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "HouseModel.h"
#import "HouseProto.h"

@implementation HouseModel
+ (nullable instancetype)modelWithHouseProto:(HouseProto *)prototype
{
    return [[self alloc] initWithHouseProto:prototype];
}
- (nullable instancetype)initWithHouseProto:(HouseProto *)prototype
{
    NSParameterAssert(prototype);
    if (!(self = [super init])) {
        return nil;
    }
    [self propertyMapWithPrototype:prototype mapping:@{@"area" : @"area",
                                                       @"isSchoolDistrict" : @"isSchoolDistrict",
                                                       @"location" : @"location"}];
    return self;
}
@end
