//
//  PetModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class PetProto;

NS_ASSUME_NONNULL_BEGIN

@interface PetModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite, assign) UInt32 limbs;
@property (nonatomic, readwrite, copy) NSString *color;
+ (nullable instancetype)modelWithPetProto:(PetProto *)prototype;
- (nullable instancetype)initWithPetProto:(PetProto *)prototype;
@end

@interface PetModel (Extension)
- (PetProto *)initializerPreprocess:(PetProto *)preprocess;
@end

NS_ASSUME_NONNULL_END
