//
//  PetModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "PetModel.h"
#import "PetProto.h"

@implementation PetModel
+ (nullable instancetype)modelWithPetProto:(PetProto *)prototype
{
    return [[self alloc] initWithPetProto:prototype];
}
- (nullable instancetype)initWithPetProto:(PetProto *)prototype
{
    NSParameterAssert(prototype);
    if (!(self = [super init])) {
        return nil;
    }
    PetProto *preprocess = [self initializerPreprocess:prototype];
    [self propertyMapWithPrototype:prototype mapping:@{@"name" : @"name",
                                                       @"color" : @"color"}];
    self->_limbs = [@([preprocess.limbs intValue]) unsignedIntValue];
    return self;
}
@end

@implementation PetModel (Extension)
- (PetProto *)initializerPreprocess:(PetProto *)preprocess
{
    return preprocess;
}
@end
