//
//  PetPbModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class PetPb;

NS_ASSUME_NONNULL_BEGIN

@interface PetPbModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite, assign) UInt32 limbs;
@property (nonatomic, readwrite, copy) NSString *color;
+ (nullable instancetype)modelWithPetPb:(PetPb *)prototype;
- (nullable instancetype)initWithPetPb:(PetPb *)prototype;
@end

@interface PetPbModel (Extension)
- (PetPb *)initializerPreprocess:(PetPb *)preprocess;
@end

NS_ASSUME_NONNULL_END
