//
//  PhoneModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class PhoneModelBuilder;
@class HeadPhoneModel;
@class AppModel;
@class WirelessChargingModel;

NS_ASSUME_NONNULL_BEGIN

@interface PhoneModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readonly, strong) NSArray<HeadPhoneModel *> *headPhone;
@property (nonatomic, readonly, strong) NSDictionary<NSString *, AppModel *> *apps;
@property (nonatomic, readonly, strong) WirelessChargingModel *charger;
@property (nonatomic, readonly, copy) NSString *price;
@property (nonatomic, readonly, assign) PhoneBrand brand;
+ (nullable instancetype)modelWithJSON:(id)json objectId:(NSString *)objectId;
- (nullable instancetype)initWithJSON:(id)json objectId:(NSString *)objectId;
- (instancetype)initWithPhoneModelBuilder:(PhoneModelBuilder *)builder;
- (instancetype)mergeWithBlock:(void(^)(PhoneModelBuilder *builder))block;
@end

@interface PhoneModelBuilder : TypewriterBaseModel
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readwrite, strong) NSArray<HeadPhoneModel *> *headPhone;
@property (nonatomic, readwrite, strong) NSDictionary<NSString *, AppModel *> *apps;
@property (nonatomic, readwrite, strong) WirelessChargingModel *charger;
@property (nonatomic, readwrite, copy) NSString *price;
@property (nonatomic, readwrite, assign) PhoneBrand brand;
- (instancetype)initWithPhoneModel:(PhoneModel *)model;
- (PhoneModel *)build;
@end

@interface PhoneModel (Extension)
+ (void)unidirectionalDataflow:(PhoneModel *)model objectId:(NSString *)objectId;
@end

NS_ASSUME_NONNULL_END
