//
//  PhoneModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "PhoneModel.h"
#import "HeadPhoneModel.h"
#import "AppModel.h"
#import "WirelessChargingModel.h"

@implementation PhoneModel
+ (nullable instancetype)modelWithJSON:(id)json objectId:(NSString *)objectId
{
    return [[self alloc] initWithJSON:json objectId:objectId];
}
- (nullable instancetype)initWithJSON:(id)json objectId:(NSString *)objectId
{
    NSParameterAssert(json);
    if (!(self = [super init])) {
        return nil;
    }
    if (![self propertyMapWithJSON:json]) {
        return nil;
    }
    self->_objectId = objectId;
    [PhoneModel unidirectionalDataflow:self objectId:self.objectId];
    return self;
}
+ (NSDictionary *)customPropertyMapper
{
    return @{@"charger" : @"accessory.charger",
             @"headPhone" : @"accessory.headPhone",
             @"brand" : @"equipment.info.phoneBrand"};
}
+ (NSDictionary *)arrayGenericClassMapper
{
    return @{@"headPhone" : @"HeadPhoneModel"};
}
+ (NSDictionary *)dictionaryGenericClassMapper
{
    return @{@"apps" : @"AppModel"};
}
- (instancetype)initWithPhoneModelBuilder:(PhoneModelBuilder *)builder
{
    NSParameterAssert(builder);
    if (!(self = [super init])) {
        return self;
    }
    [self propertyMapWithPrototype:builder mapping:@{@"objectId": @"objectId",
                                                     @"headPhone": @"headPhone",
                                                     @"apps": @"apps",
                                                     @"charger": @"charger",
                                                     @"price": @"price",
                                                     @"brand": @"brand"}];
    [PhoneModel unidirectionalDataflow:self objectId:self.objectId];
    return self;
}
- (instancetype)mergeWithBlock:(void(^)(PhoneModelBuilder *builder))block
{
    NSParameterAssert(block);
    PhoneModelBuilder *builder = [[PhoneModelBuilder alloc] initWithPhoneModel:self];
    block(builder);
    return [builder build];
}
- (void)setHeadPhone:(NSArray<HeadPhoneModel *> *)headPhone
{
    _headPhone = headPhone;
}
- (void)setApps:(NSDictionary<NSString *, AppModel *> *)apps
{
    _apps = apps;
}
- (void)setCharger:(WirelessChargingModel *)charger
{
    _charger = charger;
}
- (void)setPrice:(NSString *)price
{
    _price = price;
}
- (void)setBrand:(PhoneBrand)brand
{
    _brand = brand;
}
@end

@implementation PhoneModelBuilder
- (instancetype)initWithPhoneModel:(PhoneModel *)model
{
    NSParameterAssert(model);
    if (!(self = [super init])) {
        return self;
    }
    [self propertyMapWithPrototype:model mapping:@{@"objectId": @"objectId",
                                                   @"headPhone": @"headPhone",
                                                   @"apps": @"apps",
                                                   @"charger": @"charger",
                                                   @"price": @"price",
                                                   @"brand": @"brand"}];
    return self;
}
- (PhoneModel *)build
{
    return [[PhoneModel alloc] initWithPhoneModelBuilder:self];
}
@end

@implementation PhoneModel (Extension)
+ (void)unidirectionalDataflow:(PhoneModel *)model objectId:(NSString *)objectId
{
    // unidirectional data flow
}
@end
