//
//  UserModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class UserProto;
@class UserModelBuilder;
@class PhoneModel;
@class PetModel;
@class HouseModel;
@class ClothesModel;

NS_ASSUME_NONNULL_BEGIN

@interface UserModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) NSString *favouriteSport;
@property (nonatomic, readonly, copy) NSString *favouriteMovie;
@property (nonatomic, readonly, assign) BOOL hasMarried;
@property (nonatomic, readonly, assign) EducationLevel education;
@property (nonatomic, readonly, assign) UInt32 age;
@property (nonatomic, readonly, assign) SInt32 psychologicalAge;
@property (nonatomic, readonly, strong) NSDate *birthDate;
@property (nonatomic, readonly, strong) PhoneModel *phone;
@property (nonatomic, readonly, strong) PetModel *pet;
@property (nonatomic, readonly, strong) NSArray<HouseModel *> *houses;
@property (nonatomic, readonly, strong) NSDictionary<NSString *, NSArray<NSDictionary<NSString *, NSDictionary<NSString *, ClothesModel *> *> *> *> *wardrobes;
+ (nullable instancetype)modelWithUserProto:(UserProto *)prototype objectId:(nullable NSString *)objectId;
- (nullable instancetype)initWithUserProto:(UserProto *)prototype objectId:(nullable NSString *)objectId;
- (instancetype)initWithUserModelBuilder:(UserModelBuilder *)builder;
- (instancetype)mergeWithBlock:(void(^)(UserModelBuilder *builder))block;
@end

@interface UserModelBuilder : TypewriterBaseModel
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite, copy) NSString *favouriteSport;
@property (nonatomic, readwrite, copy) NSString *favouriteMovie;
@property (nonatomic, readwrite, assign) BOOL hasMarried;
@property (nonatomic, readwrite, assign) EducationLevel education;
@property (nonatomic, readwrite, assign) UInt32 age;
@property (nonatomic, readwrite, assign) SInt32 psychologicalAge;
@property (nonatomic, readwrite, strong) NSDate *birthDate;
@property (nonatomic, readwrite, strong) PhoneModel *phone;
@property (nonatomic, readwrite, strong) PetModel *pet;
@property (nonatomic, readwrite, strong) NSArray<HouseModel *> *houses;
@property (nonatomic, readwrite, strong) NSDictionary<NSString *, NSArray<NSDictionary<NSString *, NSDictionary<NSString *, ClothesModel *> *> *> *> *wardrobes;
- (instancetype)initWithUserModel:(UserModel *)model;
- (UserModel *)build;
@end

@interface UserModel (Extension)
+ (void)unidirectionalDataflow:(UserModel *)model objectId:(NSString *)objectId;
@end

NS_ASSUME_NONNULL_END
