//
//  UserPbModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

@class UserPb;
@class UserPbModelBuilder;
@class PetPbModel;
@class HousePbModel;
@class ClothesPbModel;

NS_ASSUME_NONNULL_BEGIN

@interface UserPbModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) NSString *favouriteSport;
@property (nonatomic, readonly, copy) NSString *favouriteMovie;
@property (nonatomic, readonly, assign) BOOL hasMarried;
@property (nonatomic, readonly, assign) EducationLevel education;
@property (nonatomic, readonly, assign) UInt32 age;
@property (nonatomic, readonly, assign) SInt32 psychologicalAge;
@property (nonatomic, readonly, strong) PetPbModel *pet;
@property (nonatomic, readonly, assign) BOOL hasPet;
@property (nonatomic, readonly, strong) NSArray<HousePbModel *> *houses;
@property (nonatomic, readonly, strong) NSDictionary<NSString *, ClothesPbModel *> *wardrobes;
+ (nullable instancetype)modelWithUserPb:(UserPb *)prototype objectId:(nullable NSString *)objectId;
- (nullable instancetype)initWithUserPb:(UserPb *)prototype objectId:(nullable NSString *)objectId;
- (instancetype)initWithUserPbModelBuilder:(UserPbModelBuilder *)builder;
- (instancetype)mergeWithBlock:(void(^)(UserPbModelBuilder *builder))block;
@end

@interface UserPbModelBuilder : TypewriterBaseModel
@property (nonatomic, readwrite, copy, nullable) NSString *objectId;
@property (nonatomic, readwrite, copy) NSString *name;
@property (nonatomic, readwrite, copy) NSString *favouriteSport;
@property (nonatomic, readwrite, copy) NSString *favouriteMovie;
@property (nonatomic, readwrite, assign) BOOL hasMarried;
@property (nonatomic, readwrite, assign) EducationLevel education;
@property (nonatomic, readwrite, assign) UInt32 age;
@property (nonatomic, readwrite, assign) SInt32 psychologicalAge;
@property (nonatomic, readwrite, strong) PetPbModel *pet;
@property (nonatomic, readwrite, assign) BOOL hasPet;
@property (nonatomic, readwrite, strong) NSArray<HousePbModel *> *houses;
@property (nonatomic, readwrite, strong) NSDictionary<NSString *, ClothesPbModel *> *wardrobes;
- (instancetype)initWithUserPbModel:(UserPbModel *)model;
- (UserPbModel *)build;
@end

@interface UserPbModel (Extension)
+ (void)unidirectionalDataflow:(UserPbModel *)model objectId:(NSString *)objectId;
@end

NS_ASSUME_NONNULL_END
