//
//  WirelessChargingModel.h
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "TypewriterBaseModel.h"

NS_ASSUME_NONNULL_BEGIN

@interface WirelessChargingModel : TypewriterBaseModel<NSObject>
@property (nonatomic, readonly, copy) NSString *length;
@property (nonatomic, readonly, copy) NSString *powerSource;
@property (nonatomic, readonly, copy) NSString *manufacturerNumber;
+ (nullable instancetype)modelWithJSON:(id)json;
- (nullable instancetype)initWithJSON:(id)json;
@end

NS_ASSUME_NONNULL_END
