//
//  WirelessChargingModel.m
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

#import "WirelessChargingModel.h"

@implementation WirelessChargingModel
+ (nullable instancetype)modelWithJSON:(id)json
{
    return [[self alloc] initWithJSON:json];
}
- (nullable instancetype)initWithJSON:(id)json
{
    NSParameterAssert(json);
    if (!(self = [super init])) {
        return nil;
    }
    if (![self propertyMapWithJSON:json]) {
        return nil;
    }
    return self;
}
+ (NSDictionary *)customPropertyMapper
{
    return @{@"manufacturerNumber" : @"equipment.info.manufacturerNumber",
             @"length" : @"cableLength"};
}
- (void)setLength:(NSString *)length
{
    _length = length;
}
- (void)setPowerSource:(NSString *)powerSource
{
    _powerSource = powerSource;
}
- (void)setManufacturerNumber:(NSString *)manufacturerNumber
{
    _manufacturerNumber = manufacturerNumber;
}
@end
