//
//  AppModel.swift
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

import Foundation

public class AppModel: TypewriterBaseModel, Error, Codable {
    enum CodingKeys: String, CodingKey {
        case type
        case producer = "company"
    }
    public var type: String
    public var producer: String?
    class func modelWithJson(json: Data) throws -> AppModel {
        let model = try JSONDecoder().decode(AppModel.self, from: json)
        return model
    }
    public init(type: String, producer: String) {
        self.type = type
        self.producer = producer
    }
}
