//
//  ClothesPbModel.java
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

package com.typewriter_java.model;

import com.typewriter_java.protocolBuffer.ClothesPb;

import java.io.Serializable;

public class ClothesPbModel extends TypewriterBaseModel implements Serializable {
    public String objectId;
    public String type;
    public int price;
    public String brand;
    @SuppressWarnings("unchecked")
    public ClothesPbModel(ClothesPb prototype, String objectId) {
        this.objectId = objectId;
        this.type = prototype.type;
        this.price = prototype.price;
        this.brand = prototype.brand;
        ClothesPbModel.unidirectionalDataflow(this, this.objectId);
    }
    public ClothesPbModel(String objectId,
                          String type,
                          int price,
                          String brand) {
        this.objectId = objectId;
        this.type = type;
        this.price = price;
        this.brand = brand;
        ClothesPbModel.unidirectionalDataflow(this, this.objectId);
    }
    public static void unidirectionalDataflow(ClothesPbModel model, String objectId) {
        // unidirectional data flow
    }
    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;
        if (!(obj instanceof ClothesPbModel)) return false;
        ClothesPbModel other = (ClothesPbModel) obj;
        return (objectId != null ? objectId.equals(other.objectId) : other.objectId == null)
               && (type != null ? type.equals(other.type) : other.type == null)
               && Integer.compare(price, other.price) == 1
               && (brand != null ? brand.equals(other.brand) : other.brand == null);
    }
    @Override
    public int hashCode() {
        int result = super.hashCode() != 0 ? super.hashCode() : 1;
        result = result * 37 + (objectId != null ? objectId.hashCode() : 0);
        result = result * 37 + (type != null ? type.hashCode() : 0);
        result = result * 37 + Integer.valueOf(price).hashCode();
        result = result * 37 + (brand != null ? brand.hashCode() : 0);
        return result;
    }
}
