//
//  HouseModel.java
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

package com.typewriter_java.model;

import com.typewriter_java.prototype.HouseProto;

import java.io.Serializable;

public class HouseModel extends TypewriterBaseModel implements Serializable {
    /**
     * 平米数
     */
    public final int area;
    /**
     * 是否是学区房
     */
    public final boolean isSchoolDistrict;
    /**
     * 位置
     */
    public final String location;
    @SuppressWarnings("unchecked")
    public HouseModel(HouseProto prototype) {
        this.area = prototype.area;
        this.isSchoolDistrict = prototype.isSchoolDistrict;
        this.location = prototype.location;
    }
    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;
        if (!(obj instanceof HouseModel)) return false;
        HouseModel other = (HouseModel) obj;
        return Integer.compare(area, other.area) == 1
               && Boolean.compare(isSchoolDistrict, other.isSchoolDistrict) == 1
               && (location != null ? location.equals(other.location) : other.location == null);
    }
    @Override
    public int hashCode() {
        int result = super.hashCode() != 0 ? super.hashCode() : 1;
        result = result * 37 + Integer.valueOf(area).hashCode();
        result = result * 37 + Boolean.valueOf(isSchoolDistrict).hashCode();
        result = result * 37 + (location != null ? location.hashCode() : 0);
        return result;
    }
}
