//
//  WirelessChargingModel.java
//  Autogenerated by typewriter
//
//  Generation Date On 2018/01/08
//  Version: 1.0.0

package com.typewriter_java.model;

import com.alibaba.fastjson.annotation.JSONCreator;
import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Map;
import java.util.HashMap;

public class WirelessChargingModel extends TypewriterBaseModel implements Serializable {
    @JSONField(name = "cableLength")
    public final String length;
    public final String powerSource;
    public final String manufacturerNumber;
    public static WirelessChargingModel modelWithJSON(String json) {
        return WirelessChargingModel.fieldsMapWithJSON(json, WirelessChargingModel.class);
    }
    @JSONCreator
    public WirelessChargingModel(@JSONField(name = "powerSource") String powerSource,
                                 @JSONField(name = "cableLength") String length,
                                 @JSONField(name = "manufacturerNumber") String manufacturerNumber) {
        this.length = length;
        this.powerSource = powerSource;
        this.manufacturerNumber = manufacturerNumber;
    }
    @SuppressWarnings("unused")
    public static Map<String, String> customFieldsMapper() {
        Map<String, String> mapper = new HashMap<>();
        mapper.put("manufacturerNumber", "equipment.info.manufacturerNumber");
        return mapper;
    }
    @Override
    public boolean equals(Object obj) {
        if (obj == this) return true;
        if (!(obj instanceof WirelessChargingModel)) return false;
        WirelessChargingModel other = (WirelessChargingModel) obj;
        return (length != null ? length.equals(other.length) : other.length == null)
               && (powerSource != null ? powerSource.equals(other.powerSource) : other.powerSource == null)
               && (manufacturerNumber != null ? manufacturerNumber.equals(other.manufacturerNumber) : other.manufacturerNumber == null);
    }
    @Override
    public int hashCode() {
        int result = super.hashCode() != 0 ? super.hashCode() : 1;
        result = result * 37 + (length != null ? length.hashCode() : 0);
        result = result * 37 + (powerSource != null ? powerSource.hashCode() : 0);
        result = result * 37 + (manufacturerNumber != null ? manufacturerNumber.hashCode() : 0);
        return result;
    }
}
